server:
  port: 1001
  servlet.context-path: /customer-register # It is the root Uri eg: http://localhost:1001/customer-register/customer/addCustomer

spring:
  application:
    name: customer-application
  data:
    mongodb:
      database: Customers
      host: localhost
      port: 27017
  cache:
    type: redis
    cache-names: Customer
    redis:
      time-to-live: 60000
  redis:
    host: localhost
    port: 6379